name: Docker Builder

on:
    workflow_dispatch:
      inputs:
        tag:
          description: 'Tag for Docker image'
          required: true
          default: 'latest'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_ACCESS_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/catalogfi/solana-validator-docker:latest
            ghcr.io/catalogfi/solana-validator-docker:${{ github.event.inputs.tag }}